// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users(id, created_at, updated_at, email, hashed_passwords)
VALUES(
	gen_random_uuid(),
	NOW(),
	NOW(),
	$1,
	$2

)
RETURNING id, created_at, updated_at, email, hashed_passwords
`

type CreateUserParams struct {
	Email           string
	HashedPasswords string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPasswords)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPasswords,
	)
	return i, err
}

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUsers)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, email, hashed_passwords
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPasswords,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET email = $2,
	hashed_passwords = $3,
	updated_at = NOW()
WHERE id = $1 
RETURNING id, created_at, updated_at, email, hashed_passwords
`

type UpdateUserParams struct {
	ID              uuid.UUID
	Email           string
	HashedPasswords string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.Email, arg.HashedPasswords)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPasswords,
	)
	return i, err
}

const upgdradeUserRed = `-- name: UpgdradeUserRed :exec
UPDATE users
SET is_chirpy_red = TRUE,
	updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpgdradeUserRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upgdradeUserRed, id)
	return err
}
